export const incumbentInit = {
  organization: '',
  subsidiary: '',
  mineType: 0,
  projectName: '',
  libraryNo: '',
  positionTitle: 0,
  positionClass: 0,
  employmentNo: '',
  employmentStart: '',
  employmentEnd: '',
  resignationNo: '',
  resignationStart: '',
  resignationEnd: '',
  certificateNo: '',
  incumbentFile: [],
  incumbentFileName: '',
  isShowIncumbentPositionTitle: false,
}
